@extends('layouts.admin')

@section('title', isset($ticket) ? 'Edit Tiket' : 'Tambah Tiket')

@section('content')
    <div class="card" style="max-width: 600px; margin: 0 auto;">
        <div class="card-header">
            <h3 class="card-title">{{ isset($ticket) ? 'Edit Tiket' : 'Tambah Tiket Baru' }}</h3>
            <a href="{{ route('admin.tickets') }}" class="btn btn-secondary">Kembali</a>
        </div>

        @if ($errors->any())
            <div style="background-color: #fee2e2; color: #991b1b; padding: 16px; border-radius: 8px; margin-bottom: 20px;">
                <ul style="margin-left: 20px;">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ isset($ticket) ? route('admin.tickets.update', $ticket->ticket_code) : route('admin.tickets.store') }}" method="POST">
            @csrf
            @if(isset($ticket))
                @method('PUT')
            @endif

            @if(!isset($ticket))
            <div class="form-group">
                <label>Kode Tiket</label>
                <input type="text" name="ticket_code" class="form-control" value="{{ old('ticket_code') }}" placeholder="TK-001" required>
            </div>
            @endif

            <div class="form-group">
                <label>Jadwal Kereta (Trip)</label>
                <select name="trip_id" class="form-control" required>
                    <option value="">Pilih Jadwal</option>
                    @foreach($trips as $trip)
                        <option value="{{ $trip->trip_id }}" {{ old('trip_id', $ticket->trip_id ?? '') == $trip->trip_id ? 'selected' : '' }}>
                            {{ $trip->train_name }} - {{ \Carbon\Carbon::parse($trip->departure_time)->format('d M Y H:i') }}
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label>Pengguna</label>
                <select name="user_id" class="form-control" required>
                    <option value="">Pilih Pengguna</option>
                    @foreach($users as $user)
                        <option value="{{ $user->id }}" {{ old('user_id', $ticket->user_id ?? '') == $user->id ? 'selected' : '' }}>
                            {{ $user->name }} ({{ $user->email }})
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label>Pilih Kursi (Klik untuk memilih)</label>
                <div id="seat-map" style="display: grid; grid-template-columns: repeat(5, 1fr); gap: 10px; margin-top: 10px; background: var(--bg-hover); padding: 15px; border-radius: 8px;">
                    <!-- Seat grid will be generated by JS -->
                </div>
                <input type="hidden" name="seats_list" id="seats_input" value="{{ old('seats_list', $ticket->seats_list ?? '') }}">
                <div id="selected-seats-display" style="margin-top: 8px; font-size: 14px; color: var(--brand-color); font-weight: 600;">
                    Kursi terpilih: {{ old('seats_list', $ticket->seats_list ?? '-') }}
                </div>
            </div>

            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    const seatMap = document.getElementById('seat-map');
                    const seatsInput = document.getElementById('seats_input');
                    const display = document.getElementById('selected-seats-display');
                    
                    let selectedSeats = seatsInput.value ? seatsInput.value.split(',').map(s => s.trim()) : [];

                    // Generate Seats (A1 to D10 as example)
                    const rows = ['A', 'B', 'C', 'D'];
                    const cols = 5;

                    rows.forEach(row => {
                        for (let i = 1; i <= cols; i++) {
                            const seatId = row + i;
                            const seat = document.createElement('div');
                            seat.textContent = seatId;
                            seat.style.cssText = `
                                padding: 10px;
                                text-align: center;
                                background-color: ${selectedSeats.includes(seatId) ? 'var(--brand-color)' : 'white'};
                                color: ${selectedSeats.includes(seatId) ? 'white' : 'black'};
                                border: 1px solid #ddd;
                                border-radius: 4px;
                                cursor: pointer;
                                font-size: 12px;
                                font-weight: 600;
                            `;

                            seat.addEventListener('click', () => {
                                if (selectedSeats.includes(seatId)) {
                                    selectedSeats = selectedSeats.filter(s => s !== seatId);
                                    seat.style.backgroundColor = 'white';
                                    seat.style.color = 'black';
                                } else {
                                    selectedSeats.push(seatId);
                                    seat.style.backgroundColor = 'var(--brand-color)';
                                    seat.style.color = 'white';
                                }
                                seatsInput.value = selectedSeats.join(', ');
                                display.textContent = 'Kursi terpilih: ' + (selectedSeats.length > 0 ? selectedSeats.join(', ') : '-');
                            });

                            seatMap.appendChild(seat);
                        }
                    });
                });
            </script>

            <div class="form-group">
                <label>Total Pembayaran (Rp)</label>
                <input type="number" name="total_amount" class="form-control" value="{{ old('total_amount', isset($ticket) ? (int)$ticket->total_amount : '') }}" required>
            </div>

            <div class="form-group">
                <label>Status Tiket</label>
                <select name="status" class="form-control" required>
                    <option value="Active" {{ old('status', $ticket->status ?? '') == 'Active' ? 'selected' : '' }}>Active</option>
                    <option value="Used" {{ old('status', $ticket->status ?? '') == 'Used' ? 'selected' : '' }}>Used</option>
                    <option value="Batal" {{ old('status', $ticket->status ?? '') == 'Batal' ? 'selected' : '' }}>Batal</option>
                </select>
            </div>

            <div class="form-group">
                <label>Metode Pembayaran</label>
                <input type="text" name="payment_method" class="form-control" value="{{ old('payment_method', $ticket->payment_method ?? '') }}" placeholder="E-Wallet, Transfer Bank, dll">
            </div>

            <div class="form-group">
                <label>Status Pembayaran</label>
                <select name="payment_status" class="form-control" required>
                    <option value="pending" {{ old('payment_status', $ticket->payment_status ?? '') == 'pending' ? 'selected' : '' }}>Pending (Belum Bayar)</option>
                    <option value="paid" {{ old('payment_status', $ticket->payment_status ?? '') == 'paid' ? 'selected' : '' }}>Paid (Sudah Bayar)</option>
                    <option value="failed" {{ old('payment_status', $ticket->payment_status ?? '') == 'failed' ? 'selected' : '' }}>Failed</option>
                    <option value="expired" {{ old('payment_status', $ticket->payment_status ?? '') == 'expired' ? 'selected' : '' }}>Expired</option>
                </select>
            </div>

            <div class="form-group">
                <label>Tanggal Booking</label>
                <input type="datetime-local" name="booked_at" class="form-control" value="{{ old('booked_at', isset($ticket) ? date('Y-m-d\TH:i', strtotime($ticket->booked_at)) : '') }}" required>
            </div>

            <button type="submit" class="btn btn-primary" style="width: 100%;">{{ isset($ticket) ? 'Simpan Perubahan' : 'Tambah Tiket' }}</button>
        </form>
    </div>
@endsection
